import { type ReactNode } from "react";

import type { Metadata } from "next";

import localFont from "next/font/local";

import "./globals.css";
import { TooltipProvider } from "@/core/components/ui/tooltip";
import { MswProvider } from "@/core/mocks/configs/MswProvider";
import QueryProvider from "@/core/services/configs/query/QueryProvider";
import { cn } from "@/core/utils/helpers";

const vazirRegular = localFont({
  variable: "--vazir-regular",
  display: "swap",
  fallback: ["Tahoma", "sans-serif"],
  adjustFontFallback: "Arial",
  src: [
    {
      path: "../../public/fonts/vazir-normal/Vazir.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/vazir-normal/Vazir.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/vazir-normal/Vazir.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const vazirBold = localFont({
  variable: "--vazir-bold",
  display: "swap",
  fallback: ["Tahoma", "sans-serif"],
  adjustFontFallback: "Arial",
  src: [
    {
      path: "../../public/fonts/vazir-bold/Vazir-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/vazir-bold/Vazir-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/vazir-bold/Vazir-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={cn(
        "h-full",
        "antialiased",
        vazirRegular.className,
        vazirRegular.variable,
        vazirBold.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <TooltipProvider>
          <MswProvider>
            <QueryProvider>{children}</QueryProvider>
          </MswProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
